### ISSUE TITLE
FPS drops from version check

### ISSUE THREAD

**Issue by Dairyman** [Voopie/MazeHelper#3]
Could you change the version check to a system like:
1. On login, sent a version request with your current version
2. Answer version requests only if your version is higher/newer and add a random delay for the answer

The current implementation causes extreme FPS drops, when in a group/raid with multiple player in the same guild.

**Comment by dsanches81** [comment]
I have the same issue and gave up using the addon because it makes the game stutter really bad.

**Comment by Voopie** [comment]
Thank you for investigating!
I'm sorry this happened 😥
New version will be very soon with cutted checker

**Comment by Voopie** [comment]
New version is available [v.1.21](https://github.com/Voopie/MazeHelper/releases/tag/v.1.21)

**Comment by Voopie** [comment]
And one more: [v.1.22](https://github.com/Voopie/MazeHelper/releases/tag/v.1.22)

**Comment by Voopie** [comment]
@Dairyman @dsanches81 
A brief explanation of why this happened:
I haven't been in a raid for a very long time and everything was tested only in partys
So solution is simple: cut out version checking to hell!
And this will serve as a lesson to me
