### ISSUE TITLE
[BUG]Maze Helper window re-appearing 

### ISSUE THREAD

**Issue by Whitestone94** [Voopie/MazeHelper#5]
First of all, thank you for this wonderful addon. It's auto solver feature has only failed me once, and the efficiency it brings is truly great. The efficiency overall, even if you have to click all four, is fantastic. There's one minor bug I was hoping you could take a loot at. 

**Describe the bug**
I use the feature of not using Maze Helper on the boss fight, because I am faster spotting the right one when I can see them all at once. However, after the boss is killed, the window re-appears and I have to X it out. 

**To Reproduce**
X

**Expected behavior**
I expected the window to stay closed. 

**Screenshots**
X

**Additional context**
X

**Comment by Voopie** [comment]
Thank you for finding this bug, it seems to have fixed it, but I'll still go check it out in practice

**Comment by Whitestone94** [comment]
> Thank you for finding this bug, it seems to have fixed it, but I'll still go check it out in practice

Very cool! I will test it out later today, as I just updated the addon before leaving this comment. Thanks!

**Comment by Voopie** [comment]
Unfortunately, the new version is not on Curseforge yet, I will try to release it as soon as possible!

**Comment by Voopie** [comment]
The new version is already available (here and on Curseforge)
