### ISSUE TITLE
Change text, when u find way

### ISSUE THREAD

**Issue by Foreika** [Voopie/MazeHelper#6]
I use russian localisation, after i find way, i see russian and english text

Add button or editor to change it, i want only english text

or may be i can change in in wow files?

**Comment by Voopie** [comment]
Hey!
In the new version (1.40) I added what you asked for :)
Already available on [GitHub Releases](https://github.com/Voopie/MazeHelper/releases) and [Wago Addons](https://addons.wago.io/addons/maze-helper-mists-of-tirna-scithe)
On CurseForge it's under review now...
